url: "https://ukiyoserver.live" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ukiyo | 浮世" # the name of your site, e.g. ACME Corp.
logo: "/assets/icons/icon-512x512.png"
repository: Ukiyo-Server/Ukiyo-server.github.io
repo_info: "This site is open source. Feel free to contribute to it on GitHub!"
description: "Ukiyo is a Discord server for Japanese and English learners. We have a friendly community and a variety of resources to help you learn Japanese or English."

plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-paginate
  - jekyll-pwa-plugin

timezone: Asia/Calcutta # Set the time zone for site generation. 

show_drafts: false # Process and render draft posts.

future: false # Publish posts with a future date

unpublished: false # Render posts that were marked as unpublished

collections:
  library:
    output: true
    filter: "type:library"
  staff_members:
    output: true
    filter: "type:staff"
  guide:
    output: true
    filter: "type:guide"
  resource:
    output: true
    filter: "type:resource"

webmaster_verifications:
  google: G-J3T9CBFLC3
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234
  # facebook: 1234

postcss:
  cache: true

paginate: 9
paginate_path: "/blogs/page-:num/"

twitter:
  username: Ukiyoserver
  card: summary_large_image

facebook:
  publisher: https://www.facebook.com/UkiyoServer

social:
  name: Ukiyo Server
  links:
    - https://www.facebook.com/UkiyoServer/
    - https://www.instagram.com/ukiyoserver/
    - https://github.com/Ukiyo-Server
    - https://twitter.com/UkiyoServer
    - https://discord.gg/ukiyo-fu-shi-937243464079400990

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

include: 
  - ".well-known"
  - "node_modules/tailwindcss"

permalink: /:categories/:year-:month-:day/:title:output_ext

plugins_dir: _plugins

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

exclude: [CONTRIBUTING.md, README.md, Gemfile, Gemfile.lock, node_modules, package.json, package-lock.json, yarn.lock, .gitignore, .gitattributes, .editorconfig, .jekyll-metadata, .sass-cache, .vscode, .vs, .DS_Store, .env, .env.example, .env.sample, .env.production, .env.development, .env.test, CNAME, CODE_OF_CONDUCT.md, CONTRIBUTING.md, postcss.config.js, README-DEV.md, SECURITY.md, tailwind.config.js, LICENSE]
keep_files: [404.html, ./.well-known/assetlinks.json,]