#
# This file contains configuration flags to customize your site
#

# Name of your site
title: Ukiyo | 浮世
SEOTitle: Ukiyo

header-img: asset/ukiyo_ico.ico

email: mailidleboy@gmail.com
# Short bio or description (displayed in the header)
description: "It is a Chill Japanese - English exchange server."

keyword: "Ukiyo, Ukiyo server, Ukiyo server owner, Japanese, Japanese server, Discord server, JLPT"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://ukiyo-server.github.io" 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# Exclude these files from your production _site
exclude: ["README.md","README.jp.md"]

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
 
name: Generate sitemap 

on:
  push:
    branches: [ staging ]
    paths: [ '**.htm', '**.pdf' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://ukiyo-server.github.io/
    
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.2
      with:
        title: "Automated sitemap update"
        body: > 
          Automated changes. Sitemap updated by 
          the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  
        commit-message: "Automated sitemap update."
        author: idleboy4038 <mailidleboy@gmail.com>
        committer: idleboy4038 <mailidleboy@gmail.com>
        branch: create-pull-request/sitemap
        delete-branch: true
